### ISSUE TITLE
[BUG] ilcorsaronero

### ISSUE THREAD

**Issue by bloodysneaker** [LightDestory/qBittorrent-Search-Plugins#14]
Hi,

got a bug with the search plugin for ilcorsaronero.
When I search a torrent and try to download it, it wont be added.
If I click RMB on the search result ->copy->download link it copies an https link with wrong syntax like:
https%3A//ilcorsaronero.link/tor/xxxxxx/****

(I think that the site didn't even host .torrent itself)

qBittorrent's Version: 4.5.0 via WebUI on docker
Python's Version: ASUSTOR 3.10.6.r10 
Plugin's name and version: ilcorsaronero 1.2

Thank you for your work

**Comment by bloodysneaker** [comment]
Proposed a solution, opened a pull request

**Comment by LightDestory** [comment]
You are correct, ilcorsaronero doesn't host any torrent file, any file with the provided pattern `https%3A//ilcorsaronero.link/tor/xxxxxx/****` is a description page of a torrent.

I suggest you to read the issue #13 as I have already explained what you get when you click "Copy download link"

**Comment by LightDestory** [comment]
I checked the issue, it seems that the WebUI is not running the "download_torrent" function defined on the engine. It is strange because I tested it also with the official plugins and it doesn't work. 

I think it is a qbittorrent issue.

**Comment by bloodysneaker** [comment]
I found a workaround for the webui, I'm not a coder and I never used python before, so the WA break the your plugin for non-webui downloads, but since I run qbittorrrent on a NAS, it's enough for me. Maybe you can made it "universal"
Added after row 57 
`vhex` = `re.search(r'value=\"(.{40})',tr)` to retrieve the 40 char hash/file name of the torrent file.
Changed row 61 in
`'https://itorrents.org/torrent/'+vhex.group(1)+'.torrent',` `to compose the .torrent download link.
In this way web-ui donwloads the .torrent and start the download just fine

**Comment by LightDestory** [comment]
I have a unofficial fix, try this [version](https://gist.github.com/LightDestory/d013693b529a8af29a3015981ac49e5d)

I am not releasing it as official because I don't think it is the proper way to handle it, it is a dirty workaround.

I hope qbit devs will sort out this issue quickly.

**Comment by LightDestory** [comment]
Closing with d42f89d8ca012bf5e16ccc2c31bf2b3327d10da9

You can now use WebUI
