### ISSUE TITLE
[BUG] Kickasstorrents

### ISSUE THREAD

**Issue by colemar** [LightDestory/qBittorrent-Search-Plugins#19]
Zero results.
Search term examples:
- mandalorian
- water

**Your Environment**
- **qBittorrent's Version:** 4.5.2
- **Python's Version:** 3.10.6
- **Plugin's name and version:** Kickasstorrents 1.1

**Comment by LightDestory** [comment]
Unfortunately KATCR is now using cloudflare anti-bot protection.

There is not a stable and free solution to bypass such protection, so unfortunately I must flag the plugin as "not working or unstable".
