### ISSUE TITLE
YourBittorrent needs updating

### ISSUE THREAD

**Issue by hdcTenBasePid** [LightDestory/qBittorrent-Search-Plugins#2]
There is some new formatting added to the torrent name (additional coloring) on the YourBittorrent site.
It makes the qBittorrent Search results look a bit messy.

The fix is to change _url_titles.group(2)_ in the ___findTorrents_ method to the following:
`url_titles.group(2).replace("<b>", "").replace("</b>", "") .replace("<span style=color:#39a8bb>", "").replace("</span>","")`

I hope that's not too sloppy for you.
Thanks for the good work, have fun.

**Comment by LightDestory** [comment]
The issue has been fixed with your suggested solution.
I have unsuccessfully tried to find a way to avoid such hard-coded replace statement but this is so stupid that it is hard to handle with regex.

Thanks for your feedback.
