### ISSUE TITLE
[BUG] AcademicTorrents

### ISSUE THREAD

**Issue by 3xploiton3** [LightDestory/qBittorrent-Search-Plugins#20]
**Describe the bug**
always error -1

**Your Environment**
- **qBittorrent's Version:** 4.5.4.10 x64
- **Python's Version:** 3.11.4 / qBittorrent Suggested
- **Plugin's name and version:** AcademicTorrents 1.2

![image](https://github.com/LightDestory/qBittorrent-Search-Plugins/assets/19517680/d19a1452-2586-42b3-bf54-565a4253ab40)

**Comment by LightDestory** [comment]
That's not an error.
AccademicTorrents provides a database.xml that doesn't contains any information about seeds and peers. So the plugin puts "-1" as replacement.
