### ISSUE TITLE
[BUG] Il Corsaro Nero

### ISSUE THREAD

**Issue by Bhaalspawn** [LightDestory/qBittorrent-Search-Plugins#21]
**Describe the bug**
Non funziona. ricerche senza risultato

**Your Environment**
- **qBittorrent's Version:** 4.5.1
- **Python's Version:** qBittorrent Suggested
- **Plugin's name and version:** Il Corsaro Nero 1.5

Ho aggiornato la versione di base perchè non funzionava ma nemmeno questa funziona. So che il sito è spesso down, ma al momento funziona e ho provato a cercare qualcosa che c'è di sicuro e su qBittorrent non esce niente.

**Comment by torto85** [comment]
Stesso problema, il sito funziona ma il risultato della ricerca è vuoto.
gli altri plugin funzionano correttamente

**Comment by LightDestory** [comment]
I am sorry about the late fix but I didn't receive any alert about this issue via email.

The issue should be fixed with 22c789476bdf909ad50d24e8bc3f6f303df78d3f

I am closing this issue.

Thanks for the report.
