### ISSUE TITLE
[BUG] YourBittorrent doesn't work

### ISSUE THREAD

**Issue by Pocokk** [LightDestory/qBittorrent-Search-Plugins#23]
**Describe the bug**
I used the search, found an item, clicked on it, it highlights that row (pink), yet nothing happens: doesn't load, doesn't give error message.

**Your Environment**
- **qBittorrent's Version:** 4.6.2 64-bit
- **Python's Version:**  3.11
- **Plugin's name and version:** YourBittorrent 1.4 (freshly downloaded)

P.S: When I click on "copy URL", I get this as a result: https://yt.0c.gay/down/42205032.torrent and when I insert it into the browser address bar, it says Error code: SSL_ERROR_UNRECOGNIZED_NAME_ALERT (latest Firefox)

**Comment by LightDestory** [comment]
It seems that I wrongly hardcoded the download path for the torrents.

I reverted back my latest modification, now the download path will be actively searched for again.

Please uninstall 1.4 and reinstall. This version has been reverted to 1.3


Close this issue if the problem has been solved on your end.

Regards, LightDestory.

**Comment by Pocokk** [comment]
Thank you, it works fine!
