### ISSUE TITLE
[BUG] btetree not precise

### ISSUE THREAD

**Issue by Pocokk** [LightDestory/qBittorrent-Search-Plugins#25]
**Describe the bug**
Same as AcademicTorrents, when I search for a name, btetree lists a bunch of unrelated results, see the picture below.

Can it be "smarten up" a little?

**Your Environment**
- **qBittorrent's Version:** v4.6.2 64-bit
- **Python's Version:** 3.11
- **Plugin's name and version:** btetree 1.3

![btetree](https://github.com/LightDestory/qBittorrent-Search-Plugins/assets/81096046/7465eee5-683c-4e82-ae37-b7d90b453b2a)

**Comment by LightDestory** [comment]
This issue is the same as #24 

I am appending the same response:

> My plugins make use of the website search engine itself, it does not implement any logic to alter the results from the source.
> If you try to use these keywords on accademictorrent's website you will get unrelated results too.
> It is by design to not implement unrelated logic on the plugins.
> This is not a bug on my end, you should ask the website's owner to smart up their search engine.
> Regards, LightDestory.

**Comment by Pocokk** [comment]
Thank you for the answer, didn't/wasn't sure how it worked actually.
