### ISSUE TITLE
[BUG] snowfl not showing

### ISSUE THREAD

**Issue by grolongo** [LightDestory/qBittorrent-Search-Plugins#28]
**Describe the bug**
Not sure why but snowfl plugin doesn't show up in the list of installed plugins in qbittorrent despite being installed alongside other plugins. I'm using a couple of your other plugins and they show up as expected.

**Your Environment**
- **qBittorrent's Version:** Windows v4.6.6
- **Python's Version:** 3.12.5
- **Plugin's name and version:** snowfl 1.4 (latest)

**Comment by LightDestory** [comment]
It seems that PR #27 broke the plugin. I have reverted such changes and now the plugin is back to 1.3. I tested it and it seems to work.

Let me know

**Comment by grolongo** [comment]
I confirm it now works. Thank you!
