### ISSUE TITLE
Search plugins update

### ISSUE THREAD

**Issue by Bhaalspawn** [LightDestory/qBittorrent-Search-Plugins#3]
Glotorrents doesn't work, the site www.gtdb.to doesn't work but glodls.to is up (not www.glodls.to that seems to be a different tracker)
i also can't fin Rarbg in the list of downloads on https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins

**Comment by LightDestory** [comment]
Thanks for your feedback. 
GloTorrents' plugin has been fixed with 11a8a5ec032b67f15de715d258ebead7a12e5711

Regarding the official list, I often forget to update it because it is outside my repository, so if you want you can update it yourself.

**Comment by Bhaalspawn** [comment]
Ma sei italiano? 

Ah si bastava mettere il puntatore sul nick.
Cmq Glotorrents l'avevo fixato da solo cambiando indirizzo appunto, ma con rarbg non funziona. Bisognerà fare altre modifiche ma non ci capisco niente.

**Comment by LightDestory** [comment]
Per favore, sii più chiaro nell'esporre i problemi. La tua issue riguardava il dominio obsoleto per GloTorrents. 
Per RarBG hai semplicemente sottolineato la mancata presenza nella lista non ufficiale, ma dalla tua precedente risposta pare che anche RarBG sia al momento non funzionante...

**Comment by Bhaalspawn** [comment]
Iniziate a metterlo nella lista ufficiale così poi uno può dire se funziona o no.
Il fatto che non funzioni potrebbe dipende dal fatto che io ho preso quello sbagliato o magari non ho fatto bene le cose, visto che non ho semplicemente dovuto scaricarlo da li

**Comment by LightDestory** [comment]
Non vi è una lista **ufficiale**, quella è, come dice anche il nome, una lista __non ufficiale__ di plugins, dove non vi è nessuna garanzia sul funzionamento e/o l'aggiornamento. 

La mancata aggiunta della voce nella lista è una mia mancanza, ma nella istruzioni del mio repo ho inserito tutte le informazioni su come poter installarle i plugin. 

Se l'installazione è andata a buon fine, appare nella lista dei plugins di qBittorrent, il problema potrebbe essere l'abuso delle query di ricerca, che ho ben descritto nelle note :)

**Comment by Bhaalspawn** [comment]
il problema è che "come installare un plugin" prevede scaricarlo da li

Per modificare Glotorrents avevo creato un nuovo txt e poi copiato dentro il testo, modificanto l'URL e basta, e poi cambiando da txt in py.
Ma se faccio la stessa cosa con Rarbg mi dice che l'estensione non è supportata, quindi non posso provare a cambiare indirizzo. e posso solo installare quella versione che non funziona

Stai usando il sito www.rarbg.is che rimanda a un proxy e all'interno di qbittorrent non mi restituisce alcun risultato.
Io uso rarbg.to; funziona e non rimanda da nessuna parte

**Comment by LightDestory** [comment]
Tutti i domini di rarbg sono protetti da un sistema antispam. Come ho descritto nelle note, un abuso delle query di ricerca porta a un blocco temporaneo. 
![image](https://user-images.githubusercontent.com/5560558/144754355-de67b631-dd7e-4dcd-9d94-412dffa16a12.png)

Quando esegui una ricerca il plugin cerca di leggere fino a 10 pagine, ergo esegui 10 richieste per query.
RARBG è un engine problematico che ho voluto integrare alla mia collezione solo per completezza, sarebbe da evirare.

**Comment by Bhaalspawn** [comment]
ma la cosa del captcha c'è solo nei proxy
prova ad usare rarbg.to

**Comment by LightDestory** [comment]
Guarda il link che ho evidenziato nello screenshot :)

**Comment by LightDestory** [comment]
Chiudo in quanto i problemi in OP sono stati risolti.

**Comment by Bhaalspawn** [comment]
a me con rarbg.to non lo fa e cmq quello messo nell'elenco è ancora rarbg.is
