### ISSUE TITLE
[PLUGIN REQUEST] mircrew

### ISSUE THREAD

**Issue by dga4130-renato** [LightDestory/qBittorrent-Search-Plugins#30]
Ciao, si puo' creare un plugin per la ricerca su mir o icv ?

**Comment by LightDestory** [comment]
Entrambi i siti, oltre ad essere privati nel senso che richiedono un login, hanno la struttura di un forum che rende più difficile la navigazione. Se non ricordo male, icv prevede pure la funzione di dover ringraziare il topic prima di accedere al download.

Seppur possibile, sviluppare plugin per questi 2 richiederebbe più tempo e manutenzione, il che non li rende adatti per il mio workflow.
