### ISSUE TITLE
corsaronero

### ISSUE THREAD

**Issue by dga4130-renato** [LightDestory/qBittorrent-Search-Plugins#31]
Buongiorno, il plugin corsaronero ha smesso di funzionare purtroppo.
Il sito e' stato rifatto completamente ed il plugin non trova nulla.
Se fosse possibile dare un'occhiata te ne sarei grato.

**Comment by LightDestory** [comment]
Problema risolto con 0c9c7cbafbc0966ecd05064aa1ab2c3a1de9621a.


Chiudo
