### ISSUE TITLE
[PLUGIN REQUEST] TntVillage

### ISSUE THREAD

**Issue by dasaferi** [LightDestory/qBittorrent-Search-Plugins#4]
**Fill the following form:**

- **Engine's name:** TntVillage
- **Engine's website:** [TntVillage](http://tntvillage2.altervista.org/)

Salve potreste fare un plugin per TntVillage? io ci ho provato ma non sono bravo con python e non ci sono riuscito, ho visto che avete fatto in passato altri plugin italiani e ho aperto questa richiesta (non urgente, quando potete farlo o  se potete farlo) per la creazione del plugin per qbittorrent. grazie mille per aver creato gli altri plugin come il corsaronero, buona giornata.

inoltre esiste un dump ufficiale del sito https://github.com/edoardopigaiani/tntvillage-release-dump in cui sono racchiuse tutte le informazioni che i siti come quello che ho linkato usano.

**Comment by LightDestory** [comment]
Aggiunto alla collezione, 38713c04f66435ff4ad62ec16c74bc55ac17681c.

Il plugin non si basa su nessun sito web, ho integrato il dump csv in locale. Questa scelta favorisce l'indipendenza da eventuali implementazioni terze di ricerca ma appesantisce il plugin stesso, pesa infatti 20MB!

Chiudo.

**Comment by dasaferi** [comment]
grazie mille, sei stato gentilissimo.
