### ISSUE TITLE
[BUG] TNTVillageDump  Fix url descrizione pagina

### ISSUE THREAD

**Issue by Slypers** [LightDestory/qBittorrent-Search-Plugins#6]
**Describe the bug**
Salve ho scoperto da poco dell'esistenza del plguin di TNTvillage #4 tramite una ricerca su google, ho notato che alcune funzioni di qBittorrent non funzionano e mi sono messo a risolvere queste cose (apri/url descrizione pagina non esistente e copia collegamento download [ancora non risolto] ) per risolvere il problema con apri/url descrizione pagina "ho implementato" la colonna TOPIC del file `tntvillage-release-dump.csv` al momento ho scritto solo 4 righe del dump nel file python perchè non ho capito come è stato generato quel database nel file python, e ho modificato la riga di codice 'desc_link in `'desc_link': "https://web.archive.org/web/20190626192255/http://forum.tntvillage.scambioetico.org/index.php?showtopic="+str(torrent[3])` per quanto riguarda la copia del collegamento download credo sia questa la voce da modificare `'link': torrent[0],` e aggiungere la roba che contiene il print di sotto perchè al momento copia solo l'hash.

allego il file python così da provare le modifiche che "ho fatto".
[tntvillagedump.zip](https://github.com/LightDestory/qBittorrent-Search-Plugins/files/7971555/tntvillagedump.zip)

**Your Environment**
- **qBittorrent's Version:** 4.3.9
- **Python's Version:** Custom / qBittorrent 4.3.9
- **Plugin's name and version:** TNTVillageDump

**Comment by LightDestory** [comment]
Le parti da te citate sono state volutamente disabilitate in quanto non esiste più un sito a cui fare riferimento per TNTVillage.

La soluzione da te adottata per forzare il link della pagina ai backup di archive non funzionerà sempre. Web Archive richiede la data dello snapshots e non hai la certezza che tutte le pagine di TNTVillage siano state "salvate" lo stesso giorno.

Data la mole di release, non ho trovato ne il tempo ne l'esigenza di controllare link per link la validità di una reference forzata su web archive.

La copia dell'hash come collegamento di download è un trick per poter avviare il download. Non essendoci più pagine facilmente raggiungibili, mi faccio passare l'hash e creo un magnet link sul momento :)

**Comment by LightDestory** [comment]
Hmm ho visto la documentazione del dump e lì non viene richiesta alcuna data, appena ho tempo proverò a rigenerare il dump per permettere il link della pagina, ma per il collegamento download non ci sono altre alternative.

**Comment by LightDestory** [comment]
Feature aggiunta con 65fd26e595b09af5032ef7fc00ff70dc73ad0289

Chiudo.

PS: La prossima volta manteniamo il tutto in inglese :)

**Comment by Slypers** [comment]
> Feature aggiunta con [65fd26e](https://github.com/LightDestory/qBittorrent-Search-Plugins/commit/65fd26e595b09af5032ef7fc00ff70dc73ad0289)
> 
> Chiudo.
> 
> PS: La prossima volta manteniamo il tutto in inglese :)

va bene, grazie mille, scusatemi tanto.
